name = "dark-smoke-1517"
type = "webpack"
workers_dev = true
account_id = "f33eebb3d1381c6a59b4834e0a5c4d3b"
zone_id = "9566903e28ff3240075f18b5a34d243d"
kv_namespaces = [
    { binding = "BUCKET", preview_id = "fe245768503d4c32b2cbdecfe57fda77", id = "e5cea7382b8e44519d9677ef40dcaeb1" }
]

[env.staging]
name = "drive-staging"

